# Generated by Django 5.1.1 on 2025-04-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nome_categoria", models.CharField(max_length=100)),
                ("descricao_categoria", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                ("id_fornecedor", models.AutoField(primary_key=True, serialize=False)),
                ("nome_fornecedor", models.CharField(max_length=150)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id_marca", models.AutoField(primary_key=True, serialize=False)),
                ("nome_marca", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id_produto", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade_estoque", models.IntegerField(default=0)),
                ("data_validade", models.DateField(blank=True, null=True)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="app.categoria",
                    ),
                ),
                (
                    "id_marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="app.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="Produto_Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prazo_entrega", models.CharField(max_length=50)),
                (
                    "id_fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.fornecedor"
                    ),
                ),
                (
                    "id_produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.produto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto-Fornecedor",
                "verbose_name_plural": "Produtos-Fornecedores",
                "unique_together": {("id_produto", "id_fornecedor")},
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="fornecedores",
            field=models.ManyToManyField(
                through="app.Produto_Fornecedor", to="app.fornecedor"
            ),
        ),
    ]
