version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - DJANGO_SETTINGS_MODULE=PI_2.settings
    networks:
      - app-network
    depends_on:
      - db
  
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avocado123
      POSTGRES_DB: dbpi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: