name: Azure Django CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite execução manual pelo GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Django Application
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run migrations
        run: |
          python manage.py migrate
          
      - name: Run tests
        run: |
          python manage.py test

  deploy:
    needs: test  # Só executa o deploy se os testes passarem
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Deploy to Azure App Service
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Prepare deployment scripts
        run: |
          chmod +x deployment/azure_startup.sh
          chmod +x startup.sh
          
      - name: Create app settings file
        run: |
          cat > .env << 'EOL'
          DJANGO_ENV=prod
          DJANGO_SETTINGS_MODULE=core.settings.prod
          SCM_DO_BUILD_DURING_DEPLOYMENT=true
          WEBSITE_WEBDEPLOY_USE_SCM=false
          EOL
          
      # Create startup.txt for Linux App Service
      - name: Create startup command file for Linux App Service
        run: |
          echo "gunicorn core.wsgi:application --bind=0.0.0.0:8000 --workers=3 --timeout=120" > startup.txt
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'autoItaApp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .