name: Azure Django CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite execução manual pelo GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Django Application
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run migrations
        run: |
          python manage.py migrate
          
      - name: Run tests
        run: |
          python manage.py test

  deploy:
    needs: test  # Só executa o deploy se os testes passarem
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Deploy to Azure App Service
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create App Service deployment files
        run: |
          # Create proper startup command file for Linux App Service
          echo "gunicorn --bind=0.0.0.0:8000 core.wsgi:application" > startup.txt
          
          # Create .deployment file to specify custom deployment script
          echo "[config]" > .deployment
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> .deployment
          
          # Fix permissions for deployment scripts
          chmod +x deployment/azure_startup.sh
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'autoItaApp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .