name: Django CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: avocado123
          POSTGRES_DB: dbpi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Migrations
      env:
        DB_HOST: localhost
      run: |
        cd PI_2
        python manage.py migrate
        
    - name: Run Tests
      env:
        DB_HOST: localhost
      run: |
        cd PI_2
        python manage.py test

  # Uncomment when ready to deploy to a staging/production environment
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy to Server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd /path/to/project
  #           git pull
  #           source projeto/bin/activate
  #           pip install -r requirements.txt
  #           cd PI_2
  #           python manage.py migrate
  #           python manage.py collectstatic --noinput
  #           sudo systemctl restart gunicorn  # Or your preferred service